# Interface schema
# https://firefox-source-docs.mozilla.org/toolkit/components/extensions/webextensions/schema.html
# possible types are here
# - https://searchfox.org/mozilla-central/source/toolkit/components/extensions/Schemas.jsm#2418-2426
#
# - properties
# - functions
# - events
# - types
#
# - type property:
#   boolean, integer, number, string, array, object, or any.
#

---
- namespace: testingOverrides
  description: Accesses preferences used to set studySetup testing flags

  functions:
  - name: getVariationNameOverride
    type: 'function'
    async: true
    description: ''
    parameters: []
  - name: getFirstRunTimestampOverride
    type: 'function'
    async: true
    description: ''
    parameters: []
  - name: getExpiredOverride
    type: 'function'
    async: true
    description: ''
    parameters: []
  - name: listPreferences
    type: 'function'
    async: true
    description: ''
    parameters: []
